pipelines:
    branches:
        default:
            - step:
                script:
                    - git init
                    - git config user.email elvis.oliveira@blive-ti.com.br
                    - git config user.name "Elvis Oliveira"
                    - git remote remove origin
                    - git remote add origin https://github.com/elvisoliveira-blive/jenkins_integration.git
                    - git pull origin master
                    - git add .
                    - git commit -m "$(hg log --limit 1 | grep summary | cut -d ':' -f 2 | awk '{$1=$1};1')"
                    - git push https://'elvisoliveira-blive':'blive%40123'@github.com/elvisoliveira-blive/jenkins_integration.git --all